state_dimension: 1081 # Lidar 1081
action_dimension: 2
learning_rate: 0.001
gamma: 0.99
alpha: 0.8
batch_size: 256
num_episodes: 1000
max_steps: 1000
hidden_layer: 2048

targetbox_distance: 0.8
collision_distance: 0.2
reward_target: 200
reward_collision: -20
